### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [ElenaLaufeyson/Ciphering#1]
1. Вынесите функциональность шифрации/дешифрации входного потока в выходной из функции `main()` как минимум, для того, чтобы эту часть функциональности можно было протестировать отдельно.
2. Классы `CheckArg` и `Data` видится логичным объединить в один класс, конструктор которого принимает аргументы командной строки и отдаёт параметры из класса `Data` с помощью геттеров.
```java
Params p = new Params(args);
String key = p.getKey();
```
3. Старайтесь соблюдать конвенции об именовании в Java. В частности, слова в названиях полей, переменных, классов, отделяются регистром `inputname` -> `inputName`, `Ciphxor` -> `CiphXor` и т. д.
4. Вы неправильно интерпретируете ключ. Ключ из командной строки -- это последовательность байт, заданная в шестнадцатеричном виде, а не последовательность символов, которые могут встречаться в шестнадцатеричном числе. То есть, ключ `CAFE` -- это ключ из двух байт: `1100 1010 1111 1110`, а не из четырёх, как у вас.
5. В связи с этим нужно дополнительно проверять, что в качестве ключа передано целое число байт: `BAD` -- некорректный ключ.

**Comment by ElenaLaufeyson** [comment]
Исправила замечания.

**Comment by gagarski** [comment]
1. Замечание №1 всё ещё актуально.
2. Не вижу тестов в репозитории
3. В большинстве утилит командной строки порядок аргументов произвольный, хотелось бы чтобы тут тоже было так. Можете использовать библиотеку для парсинга аргументов (см. лекцию), тогда это сразу заработает.
4. Старайтесь не использовать веб-интерфейс GitHub для отправки изменений. Это создаёт кучу лишних коммитов (по одному на файл). В проектах хоть немного больше этого отправлять вручную через веб-интерфейс практически нереально. Если есть проблемы с настройкой git, пишите или подходите - будем смотреть.

**Comment by gagarski** [comment]
5. Проверку на чётность количества шестнадцатеричных цифр в ключе можно было добавить прямо в регулярное выражение.

**Comment by ElenaLaufeyson** [comment]
По поводу замечания №1 - функциональность шифрации/дешифрации входного потока в выходной из функции main() уже была ранее вынесено мною в отдельную функцию convert. Насчет порядка аргументов в командной строке - мне было выдано задание, в котором четко описано, как выглядит командная строка, а также, в каком порядке в ней расположены аргументы: "Command Line: ciphor [-c key] [-d key] inputname.txt [-o outputname.txt]", поэтому я не понимаю, почему Вы меняете задание по ходу его выполнения... Тесты я добавила, проверку на чётность также перебросила в функцию проверки ключа.

**Comment by gagarski** [comment]
> По поводу замечания №1 - функциональность шифрации/дешифрации входного потока в выходной из функции main() уже была ранее вынесено мною в отдельную функцию convert.

Я имел в виду подобие вашего класса `CiphXor`, но работающего со входными и выходными потоками (см. пример `recode` из пятой лекции). Такой класс легче тестировать (можно даже не создавая файлы в тестах).

> Насчет порядка аргументов в командной строке - мне было выдано задание, в котором четко описано, как выглядит командная строка, а также, в каком порядке в ней расположены аргументы

Во-первых, найдите какую-нибудь стандартную утилиту команднйо строки, в которой порядок аргументов жёстко задан. Во-вторых, любая библиотека для разбора аргументов позволит вам задавать флаги с аргументами в произвольном порядке, в-третьих, подумайте, насколько ваш подход с разбором аргументов переносим на формат командной строки у которого 20 необязательных невзаимоисключающих аргументов.

> проверку на чётность также перебросила в функцию проверки ключа.

"прямо в регекс" - это примерно так: `"^(([0-9A-Fa-f]{2})*)$"`

> Тесты я добавила
По поводу последнего теста: идея поXOR-ить два раза и сравнить с начальным резульатом интереса и имеет право на существование, но к сожалению этим тестом можно поймать дажеко не все баги. Представьте, что ваша функция `convert` с багом и шифрует/дешифрует только половину файла. С тагим багом ваш тест пройдёт. Можно оставить этот тест и добавить ещё один, который сравнивает результат шифрации/дешифрации с эталонным результатом из заранее заготовленного файла (даже если вы схитрите и заранее заготовите его с помощью своей же программы, это будет лучше чем ничего, поскольку позволит вам найти возможные баги после изменений вашей программы).

**Comment by ElenaLaufeyson** [comment]
Добрый вечер! Ваши замечания все я исправила, но, что касается командной строки, у меня возникли проблемы с подключением библиотеки kohsuke, поэтому подойду насчет этого к Вам завтра на практическом занятии.

**Comment by ElenaLaufeyson** [comment]
С командной строкой я также сделала все, как Вы просили, а замечания исправила.

**Comment by gagarski** [comment]
1. В всех тестах, где вы сравниваете файлы, вы делаете какие-то странные манипуляции с исключениями. Во-первых, если результат не совпал с ожидаемым, принято использовать `assertEquals` и другие методы из JUnit. Во-вторых, выбор исключения выглядит случайным. В-третьих, вы его ловите и печатаете сообщение на консоль, а тест после этого успешно проходит.
2. В классе `FileCoder` было бы логично сделать имена входного и выходного файла параметрами метода `convert()` (как в `CiphXor`)
3. Постарайтесь почитать про систему ввода/вывода в Java (опять таки, посмотреть пример `recode`) и подумать, как можно сделать ввод/вывод более универсальным. В рамках этой задачи это не очень нужно, но знать про это Java-программисту необходимо.

**Comment by ElenaLaufeyson** [comment]
Исправила последние Ваши замечания.
